# Generated by Django 6.0 on 2025-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='reports/photos/'),
        ),
    ]
