# Generated by Django 6.0 on 2025-12-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technicien'), ('SUPERVISOR', 'Superviseur')], default='TECHNICIAN', max_length=20),
        ),
    ]
