# Generated by Django 6.0 on 2025-12-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_technician_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='can_manage_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technicien'), ('SUPERVISOR', 'Superviseur'), ('SUPERADMIN', 'SuperviseurAdmin')], default='TECHNICIAN', max_length=20),
        ),
    ]
