# Generated by Django 6.0 on 2025-12-23 08:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_technician_can_manage_all_alter_technician_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='technician',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='reports.technician'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), help_text="Durée estimée pour l'exécution de la tâche"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Visible dans les dashboards opérationnels'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Créée'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('AWAITING_VALIDATION', 'En attente validation admin'), ('COMPLETED', 'Validée (finie)')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(upload_to='reports/photos/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.task'),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Auteur du rapport'), ('PARTICIPANT', 'Participant')], max_length=20)),
                ('has_validated_participation', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.technician')),
            ],
            options={
                'unique_together': {('task', 'technician')},
            },
        ),
    ]
